reload-civs: true
f-key-command: 'cv menu'
bluemap:
  show-underground-regions: false
townbar:
  payout-prefix: '$'
  payout-suffix: ''
  notification-duration: 3
trades:
#  librarian:
#    novice:
#      0:
#        input1:
#          item: PAPER
#          amount: 48
#        output:
#          item: EMERALD
#          amount: 1
#        max-uses: 4
#        villager-xp: 1
#      1:
#        input1:
#          item: EMERALD
#          amount: 3
#        output:
#          item: BOOKSHELF
#          amount: 1
#  cartographer:
#    novice:
#      0:
#        input1:
#          item: PAPER
#          amount: 48
#        output:
#          item: EMERALD
#          amount: 1
#        max-uses: 4
#        villager-xp: 1
#      1:
#        input1:
#          item: EMERALD
#          amount: 7
#        output:
#          item: MAP
#          amount: 1