name: CivsExtras
version: 2.0.0
author: JotaFaD
main: io.github.jotafad.civsextras.CivsExtras
api-version: 1.16
depend: [Civs]
softdepend:
  - GriefPrevention
commands:
  ce:
    description: Extra features for the Civs plugin
    usage: /ce
    permission: civsextras.ce